# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Radical Product
email: hello@radicalproduct.com
description: >- # this means to ignore newlines until "baseurl:"
  Join the movement that's building vision-driven products
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.radicalproduct.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: radhikadutt
logo: /img/logo.svg

# Build settings

# theme: Olania

source: src

#-------------------------------
# Author Settings
author:
  name: Radhika Dutt
  bio: Product leader and entrepreneur in the Boston area. Author of Radical Product Thinking, participated in 4 exits, 2 of which were companies I founded.
  image: "https://medium.com/@rdutt?source=follow_footer-------------------------------------/images/01.jpg"
  avatar: "https://miro.medium.com/fit/c/160/160/1*d2fA3IUJpW_GNDg40ofPmA.jpeg"

# Example of adding a new link to the section author - {name: "Github", link: "https://github.com"}
author-social:

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
#contact:
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-linkedin", link: "https://linkedin.com"}

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Gallery section (Footer)
gallery:
  name: Most Read
  images:
    - alt: "Minimalism"
      url: "/images/17.jpg"
    - alt: "Minimalism"
      url: "/images/07.jpg"
    - alt: "Minimalism"
      url: "/images/08.jpg"
    - alt: "Minimalism"
      url: "/images/22.jpg"
    - alt: "Minimalism"
      url: "/images/10.jpg"
    - alt: "Minimalism"
      url: "/images/21.jpg"
    - alt: "Minimalism"
      url: "/images/29.jpg"
    - alt: "Minimalism"
      url: "/images/30.jpg"
    - alt: "Minimalism"
      url: "/images/31.jpg"

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

paginate: 9
paginate_path: "/blog/page:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  training_posts:
    people: true
    output: true
    permalink: /:name
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
