- title: Product Management
  description: Level up as a team and translate your shared vision into everyday activities. This training helps product teams avoid getting stuck in tactical execution and helps teams think strategically to create tangible outcomes. 
  bg: 53B455
  copy: If you have one or more product teams
  img: /images/combined-shape-2.svg

- title: Digital Transformation
  description: Cultivate a new mindset in a large organization to build customer-centric products. It helps you align across your organization and offers a step-by-step approach for building transformative products.
  bg: FF7E00
  copy: If you're transforming to build user-centric products.
  img: /images/computer-svgrepo-com.svg

- title: Innovation
  description: Build successful products systematically so you iterate less and achieve more. You only have 2-3 pivots before you run out of money or momentum - this training helps you use them wisely.
  bg: FF1A4D
  copy: If you're building a new product.
  img: /images/idea-svgrepo-com.svg

- title: Product Ethics
  description: Build successful products while avoiding digital pollution or collateral damage to society. This training helps you embrace responsibility so you can build products that create the change you intend.
  bg: 3B5DEF
  copy: If you want to build equitable products.
  img: /images/combined-shape-3.svg